# frozen_string_literal: true

require 'pathname'
require 'securerandom'
require 'time'
require 'logger'

require_relative 'video_encoder/version'
require_relative 'video_encoder/domain/status'
require_relative 'video_encoder/domain/job'

require_relative 'video_encoder/persistence/database'
require_relative 'video_encoder/persistence/job_repository'

require_relative 'video_encoder/encoder/base'
require_relative 'video_encoder/encoder/fake_encoder'
require_relative 'video_encoder/encoder/ffmpeg_runner'
require_relative 'video_encoder/encoder/ffmpeg_encoder'

require_relative 'video_encoder/media_probe'
require_relative 'video_encoder/encoding_progress'
require_relative 'video_encoder/progress_parser'
require_relative 'video_encoder/progress_reporter'
require_relative 'video_encoder/encoding_monitor'
require_relative 'video_encoder/encoding_monitor_factory'

require_relative 'video_encoder/worker'
require_relative 'video_encoder/cli'
require_relative 'video_encoder/loggable'
require_relative 'video_encoder/config'
require_relative 'video_encoder/directories'
require_relative 'video_encoder/ffmpeg_config'
require_relative 'video_encoder/watcher'
require_relative 'video_encoder/verifier'
require_relative 'video_encoder/workspace'
require_relative 'video_encoder/external_dependency_checker'
require_relative 'video_encoder/external_command_probe'

require_relative 'video_encoder/media'
require_relative 'video_encoder/track'
require_relative 'video_encoder/audio_output_track'
require_relative 'video_encoder/video_track'
require_relative 'video_encoder/track_selector'
require_relative 'video_encoder/segment'
require_relative 'video_encoder/trim_project'
require_relative 'video_encoder/trim_session_loader'
require_relative 'video_encoder/convert_trim_session'
require_relative 'video_encoder/trim_project_document'
require_relative 'video_encoder/trim_project_serializer'
require_relative 'video_encoder/trim_project_loader'
require_relative 'video_encoder/mlt_project_builder'
require_relative 'video_encoder/mlt_renderer'
require_relative 'video_encoder/ffmpeg_remuxer'
require_relative 'video_encoder/trim_exporter'
require_relative 'video_encoder/workspace_cleaning_exporter'
require_relative 'video_encoder/trim_workspace'
require_relative 'video_encoder/trim_editor'
require_relative 'video_encoder/gap'
require_relative 'video_encoder/video_export_profile'
require_relative 'video_encoder/srt_normalizer'
require_relative 'video_encoder/srt_composer'
require_relative 'video_encoder/ffmpeg_subtitle_segment_extractor'
require_relative 'video_encoder/ffmpeg_subtitle_project_concatenator'
require_relative 'video_encoder/ccextractor_ocr'
require_relative 'video_encoder/subtitle_project_processor'
require_relative 'video_encoder/trim_subtitle_exporter'
require_relative 'video_encoder/command_runner'
require_relative 'video_encoder/export_trim_project'
require_relative 'video_encoder/export_trim_project_file'
require_relative 'video_encoder/trim_export_factory'
require_relative 'video_encoder/trim_project_file_export_factory'
