database: video_encoder.db

encoder: ffmpeg

directories:
  incoming: to_be_encoded
  queue: queue
  encoded: encoded
  archive: archive

ffmpeg:
  container: mkv
  video_codec: hevc_nvenc
  preset: p6
  tune: hq
  cq: 22
  rc: vbr_hq
  spatial_aq: true
  aq_strength: 8
  b_ref_mode: middle
  deinterlace: true
  audio_codec: aac
